sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t curryari/react-test -f ./client/Dockerfile.dev ./client

script:
#anything here that doesnt have exit code 0 means the test didnt pass
  - docker run -e CI=true curryari/react-test npm test

after_success:
  - docker build -t curryari/multi-client-prod ./client
  - docker build -t curryari/multi-nginx-prod ./nginx
  - docker build -t curryari/multi-server-prod ./server
  - docker build -t curryari/multi-worker-prod ./worker
#log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take images and push to docker hub
  - docker push curryari/multi-client-prod
  - docker push curryari/multi-nginx-prod
  - docker push curryari/multi-server-prod
  - docker push curryari/multi-worker-prod

deploy:
  provider: elastocbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-744189490109'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
